import {useEffect,useState} from 'react'
import {Activity,ArrowRight,CalendarDays,Check,ChevronRight,Clock,Dumbbell,HeartPulse,MapPin,Menu,MessageCircle,Phone,ShieldCheck,Target,Users,X} from 'lucide-react'
import './Landing.css'
import {balanceIllustration,mobilityIllustration,runningIllustration,strengthIllustration} from '../generatedIllustrations'
import heroSprint from '../art/heroSprint';import painBack from '../art/painBack';import painKnee from '../art/painKnee';import painShoulder from '../art/painShoulder';import painNeck from '../art/painNeck';import painSport from '../art/painSport';import painMobility from '../art/painMobility';import aboutTraining from '../art/aboutTraining';import sportTrail from '../art/sportTrail';import stageAthlete from '../art/stageAthlete';import stageAdult from '../art/stageAdult';import stageSenior from '../art/stageSenior';import stageReturn from '../art/stageReturn';import blogRunning from '../art/blogRunning';import blogAnkle from '../art/blogAnkle';import blogDesk from '../art/blogDesk';import blogActive from '../art/blogActive';import logo from '../art/logo'

const WA='https://wa.me/522723565429?text=Hola%20FYSIKO%2C%20quiero%20agendar%20una%20valoraci%C3%B3n.'
const nav=[['/','Inicio'],['/servicios','Servicios'],['/proceso','Proceso'],['/nosotros','Nosotros'],['/blog','Blog'],['/contacto','Contacto']]
const serviceArt=[mobilityIllustration,runningIllustration,strengthIllustration,balanceIllustration]
const pains=[['Dolor de espalda','Postura y zona lumbar',painBack],['Dolor de rodilla','Lesiones y sobrecarga',painKnee],['Dolor de hombro','Fuerza y movilidad',painShoulder],['Dolor de cuello','Tensión y control',painNeck],['Lesiones deportivas','Vuelve a tu actividad',painSport],['Movilidad limitada','Recupera confianza',painMobility]]
const services=[['Fisioterapia general','Valoración y plan para recuperar función.',HeartPulse],['Rehabilitación deportiva','Regresa a entrenar con seguridad.',Activity],['Traumatología y ortopedia','Recuperación muscular, articular y de fracturas.',Dumbbell],['Rehabilitación neurológica','Trabajo funcional adaptado a cada persona.',ShieldCheck]]
const steps=[['Agenda tu valoración','Cuéntanos qué necesitas y elegimos horario.'],['Evaluamos tu caso','Revisamos movilidad, historia y objetivos.'],['Plan personalizado','Definimos acciones claras para ti.'],['Seguimiento','Medimos avances y ajustamos el plan.']]
const stages=[['Deportistas','Rendimiento y prevención.',stageAthlete],['Adultos','Muévete mejor en tu día.',stageAdult],['Adultos mayores','Mantén tu independencia.',stageSenior],['Regreso a la actividad','Vuelve con confianza.',stageReturn]]
const posts=[['Entrenar sin ignorar señales','Cómo distinguir adaptación de una molestia que conviene valorar.',blogRunning],['Movilidad de tobillo','Una articulación pequeña que cambia mucho tu movimiento.',blogAnkle],['Pausas que sí ayudan','Ideas simples para moverte mejor durante el trabajo.',blogDesk],['Actividad a cualquier edad','La constancia importa más que empezar perfecto.',blogActive]]

function Logo(){return <a className="fs-logo" href="/"><img src={logo} alt="FYSIKO"/></a>}
function Header(){const[o,setO]=useState(false);useEffect(()=>{document.body.style.overflow=o?'hidden':'';return()=>{document.body.style.overflow=''}},[o]);return <header className={'fs-header '+(o?'menu-open':'')}><div className="fs-wrap fs-nav"><Logo/><nav className={o?'open':''}><div className="fs-menu-heading"><span>Menú</span><small>Fisioterapia en Orizaba</small></div><div className="fs-menu-links">{nav.map(([h,l],i)=><a onClick={()=>setO(false)} className={location.pathname===h?'active':''} href={h} key={h}><span>0{i+1}</span><strong>{l}</strong><ArrowRight/></a>)}</div><div className="fs-menu-bottom"><p>Movimiento real.<br/>Vida sin límites.</p><a className="fs-nav-cta" href={WA}>Agendar valoración</a></div></nav><a className="fs-nav-cta desktop" href={WA}>Agendar valoración</a><button className="fs-menu" onClick={()=>setO(!o)}>{o?<X/>:<Menu/>}</button></div></header>}
function Footer(){return <footer className="fs-footer"><div className="fs-wrap fs-footer-main"><div><Logo/><p>Movimiento real.<br/>Vida sin límites.</p></div><div><b>Explora</b>{nav.slice(1).map(([h,l])=><a href={h} key={h}>{l}</a>)}</div><div><b>Contacto</b><a href="tel:+522723565429">272 356 5429</a><span>Norte 6 #911, col. Centro, Orizaba, Ver.</span><a href="https://instagram.com/fysiko.rhb">@fysiko.rhb</a></div></div><div className="fs-wrap fs-legal"><span>© {new Date().getFullYear()} FYSIKO.</span><a href="/admin">Acceso administrativo</a></div></footer>}
function Transition(){return <div className="fs-transition" aria-hidden="true"><i/><div><img src={logo}/></div></div>}
function Layout({children}:{children:React.ReactNode}){useEffect(()=>{const f=(e:MouseEvent)=>{const a=(e.target as HTMLElement).closest('a') as HTMLAnchorElement|null;const h=a?.getAttribute('href');if(!h||!h.startsWith('/')||h===location.pathname)return;e.preventDefault();document.documentElement.classList.add('fs-leaving');setTimeout(()=>location.href=h,860)};document.addEventListener('click',f);return()=>document.removeEventListener('click',f)},[]);return <main className="fs-site"><Transition/><Header/>{children}<Footer/><a className="fs-wa" href={WA}><MessageCircle/></a></main>}
function Btn({children,href=WA,outline=false}:{children:React.ReactNode,href?:string,outline?:boolean}){return <a className={'fs-btn '+(outline?'outline':'')} href={href}>{children}<ArrowRight/></a>}
function Head({tag,title,copy}:{tag:string,title:string,copy?:string}){return <div className="fs-section-head"><span>{tag}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
function PageTop({tag,title,accent,copy}:{tag:string,title:string,accent:string,copy:string}){return <section className="fs-page-top"><div className="fs-wrap"><span>{tag}</span><h1>{title}<em>{accent}</em></h1><p>{copy}</p></div></section>}
function Cta(){return <section className="fs-cta"><div className="fs-wrap"><div><span>Da el primer paso</span><h2>No esperes a que el dolor te detenga.</h2></div><Btn>Agendar por WhatsApp</Btn></div></section>}

function Home(){return <Layout>
 <section className="fs-hero"><img src={heroSprint} alt="Corredor iniciando una carrera"/><div className="fs-hero-shade"/><div className="fs-wrap fs-hero-copy"><span>Fisioterapia en Orizaba</span><h1>Recupera tu<br/><em>movimiento.</em></h1><h2>Vuelve a sentirte bien.</h2><p>Valoración, rehabilitación y ejercicio para reducir dolor y volver a hacer lo que te gusta.</p><div className="fs-actions"><Btn>Agendar valoración</Btn><Btn href="/servicios" outline>Conocer servicios</Btn></div></div></section>
 <section className="fs-trust"><div className="fs-wrap"><span><HeartPulse/>Atención personalizada</span><span><Target/>Enfoque en resultados</span><span><MapPin/>Orizaba, Veracruz</span></div></section>
 <section className="fs-section"><div className="fs-wrap"><Head tag="Empieza por lo que sientes" title="¿Qué te impide moverte como antes?" copy="Identifica tu molestia y conoce cómo podemos ayudarte."/><div className="fs-pain-grid">{pains.map(p=><a href="/servicios" key={p[0]}><img src={p[2] as string} alt=""/><div><h3>{p[0]}</h3><p>{p[1]}</p><ChevronRight/></div></a>)}</div></div></section>
 <section className="fs-section fs-soft"><div className="fs-wrap"><Head tag="Nuestros servicios" title="Tratamientos pensados para tu vida"/><div className="fs-service-grid">{services.map((s,i)=>{const I=s[2] as typeof Activity;return <article key={s[0] as string}><img src={serviceArt[i]} alt=""/><div><I/><h3>{s[0] as string}</h3><p>{s[1] as string}</p><a href="/servicios">Conocer más <ArrowRight/></a></div></article>})}</div></div></section>
 <section className="fs-process-band"><div className="fs-wrap"><Head tag="Tu recuperación, paso a paso" title="Empieza con una buena evaluación"/><div className="fs-steps">{steps.map((s,i)=><article key={s[0]}><b>0{i+1}</b><h3>{s[0]}</h3><p>{s[1]}</p></article>)}</div></div></section>
 <section className="fs-about"><div className="fs-wrap"><img src={aboutTraining} alt="Dos personas entrenando"/><div><span>Sobre FYSIKO</span><h2>Tratamiento personalizado.<br/><em>Atención humana.</em></h2><p>Escuchamos tu historia, evaluamos tu movimiento y construimos un plan que tenga sentido para tu vida.</p><div className="fs-checks"><span><Check/>Objetivos claros</span><span><Check/>Progreso medible</span><span><Check/>Acompañamiento cercano</span></div><Btn href="/nosotros">Conoce FYSIKO</Btn></div></div></section>
 <section className="fs-sport"><img src={sportTrail} alt="Corredor de montaña"/><div className="fs-wrap"><span>Rehabilitación deportiva</span><h2>¿Te duele entrenar?<br/><em>No lo ignores.</em></h2><p>Entiende qué está pasando y vuelve más fuerte, seguro y preparado.</p><Btn>Valoración deportiva</Btn></div></section>
 <section className="fs-section"><div className="fs-wrap"><Head tag="Para cada momento" title="Atención en distintas etapas de vida"/><div className="fs-stage-grid">{stages.map(s=><article key={s[0]}><img src={s[2]} alt=""/><h3>{s[0]}</h3><p>{s[1]}</p></article>)}</div></div></section>
 <section className="fs-section fs-soft"><div className="fs-wrap"><Head tag="Historias reales" title="Personas que volvieron a moverse"/><div className="fs-testimonials">{[['MG','Llegué con dolor y hoy puedo trabajar y entrenar sin miedo.'],['LR','Me explicaron cada paso y el avance se sintió todos los días.'],['CT','La atención fue cercana y el plan se adaptó a mis objetivos.']].map(x=><blockquote key={x[0]}><b>“</b><p>{x[1]}</p><footer><i>{x[0]}</i><span>Paciente FYSIKO</span></footer></blockquote>)}</div></div></section>
 <section className="fs-section"><div className="fs-wrap"><Head tag="Contenido útil" title="Conocimiento para moverte mejor"/><div className="fs-blog-grid">{posts.map(p=><a href="/blog" key={p[0]}><img src={p[2] as string} alt=""/><span>Movimiento</span><h3>{p[0]}</h3><p>{p[1]}</p><b>Leer artículo <ArrowRight/></b></a>)}</div></div></section>
 <Cta/><section className="fs-section"><div className="fs-wrap fs-home-bottom"><Location/><Faq/></div></section>
 </Layout>}

function Services(){const main=[
 ['01','Fisioterapia general','Dolor, movilidad y recuperación funcional','Una valoración completa para entender qué limita tu movimiento y diseñar un tratamiento de acuerdo con tus actividades.',['Esguinces','Dolor muscular','Lumbalgia'],HeartPulse],
 ['02','Rehabilitación deportiva','Vuelve a entrenar con seguridad','Recuperación progresiva, fuerza y readaptación para regresar a tu disciplina con mayor confianza y control.',['Sobrecargas','Lesiones deportivas','Prevención'],Activity],
 ['03','Traumatología y ortopedia','Recupera función después de una lesión','Acompañamiento para lesiones musculares, articulares, fracturas y procesos indicados por especialistas.',['Fracturas','Desgarros','Articulaciones'],Dumbbell],
 ['04','Rehabilitación neurológica','Movimiento adaptado a cada persona','Trabajo funcional enfocado en movilidad, coordinación, equilibrio e independencia según cada caso.',['Coordinación','Equilibrio','Movilidad'],Target]
 ];return <Layout>
 <PageTop tag="Servicios FYSIKO" title="No se trata sólo del dolor." accent="Se trata de volver." copy="Evaluamos tu caso, entendemos lo que necesitas recuperar y construimos un plan claro para avanzar."/>
 <section className="fs-services-intro"><div className="fs-wrap"><div><span>Atención personalizada</span><h2>Un tratamiento que parte de tu vida real.</h2></div><p>No necesitas llegar sabiendo qué terapia pedir. Cuéntanos qué sientes, desde cuándo y qué actividad quieres recuperar. La valoración nos ayuda a elegir el camino adecuado.</p></div></section>
 <section className="fs-service-catalog"><div className="fs-wrap">{main.map(([num,title,kicker,copy,tags,Icon])=>{const I=Icon as typeof Activity;return <article key={title as string}><div className="fs-service-index"><b>{num as string}</b><I/></div><div className="fs-service-body"><span>{kicker as string}</span><h2>{title as string}</h2><p>{copy as string}</p><div>{(tags as string[]).map(tag=><i key={tag}>{tag}</i>)}</div></div><a href={WA} aria-label={'Consultar '+title}><ArrowRight/></a></article>})}</div></section>
 <section className="fs-conditions"><div className="fs-wrap"><Head tag="¿Qué atendemos?" title="Motivos frecuentes de consulta"/><div>{['Esguinces','Desgarros musculares','Lumbalgia','Ciatalgia','Artrosis degenerativa','Cervicalgias','Fracturas','Dolor articular','Movilidad limitada','Recuperación deportiva'].map((x,i)=><span key={x}><b>{String(i+1).padStart(2,'0')}</b>{x}</span>)}</div></div></section>
 <section className="fs-service-choice"><div className="fs-wrap"><div><span>No tienes que elegir solo</span><h2>La valoración define el punto de partida.</h2><p>Revisamos tu movilidad, antecedentes, síntomas y objetivos. Después te explicamos qué podemos trabajar, cómo y por qué.</p><Btn>Agendar valoración</Btn></div><ol>{steps.map((s,i)=><li key={s[0]}><b>0{i+1}</b><div><strong>{s[0]}</strong><span>{s[1]}</span></div></li>)}</ol></div></section>
 <Cta/></Layout>}
function Process(){return <Layout><PageTop tag="Proceso" title="Tu recuperación empieza" accent="con una buena evaluación." copy="Sin fórmulas genéricas: cuatro pasos claros y acompañamiento continuo."/><section className="fs-section"><div className="fs-wrap fs-process-list">{steps.map((s,i)=><article key={s[0]}><b>0{i+1}</b><div><h2>{s[0]}</h2><p>{s[1]}</p></div></article>)}</div></section><section className="fs-values"><div className="fs-wrap">{[['95%','Claridad sobre tu plan'],['1 a 1','Atención durante la sesión'],['100%','Enfoque personalizado']].map(x=><article key={x[0]}><b>{x[0]}</b><p>{x[1]}</p></article>)}</div></section><Cta/></Layout>}
function About(){return <Layout><PageTop tag="Nosotros" title="Movimiento real." accent="Atención humana." copy="Una forma clara, cercana y profesional de acompañar tu recuperación."/><section className="fs-section"><div className="fs-wrap fs-editorial"><div><span>Nuestra filosofía</span><h2>Tu vida no cabe en un protocolo.</h2></div><div><p>Cada persona llega con una historia y objetivos diferentes. Primero escuchamos, luego evaluamos y finalmente diseñamos.</p><p>Cada avance debe traducirse en algo real: caminar, trabajar, entrenar o volver a disfrutar.</p></div></div></section><section className="fs-values"><div className="fs-wrap">{[['01','Escuchar'],['02','Evaluar'],['03','Explicar'],['04','Acompañar']].map(x=><article key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2></article>)}</div></section><Cta/></Layout>}
function Blog(){return <Layout><PageTop tag="Blog" title="Ideas que ayudan" accent="a moverte mejor." copy="Información práctica, directa y sin recetas milagro."/><section className="fs-section"><div className="fs-wrap fs-blog-list">{posts.map((p,i)=><article key={p[0]}><b>0{i+1}</b><div><span>Movimiento · 4 min</span><h2>{p[0]}</h2><p>{p[1]} En consulta podemos valorar tu situación particular.</p><a href={WA}>Resolver una duda <ArrowRight/></a></div></article>)}</div></section><Cta/></Layout>}
function Location(){return <div className="fs-location"><span>Visítanos</span><h2>Estamos en Orizaba.</h2><div className="fs-location-list"><div className="fs-location-row"><MapPin/><div><b>Dirección</b><span>Norte 6, entre Oriente 17 y 19, #911<br/>Col. Centro, Orizaba, Veracruz</span></div></div><div className="fs-location-row"><Clock/><div><b>Horario</b><span>Lunes a sábado: 9:00 a. m. – 9:00 p. m.<br/>Domingo: 9:00 a. m. – 1:00 p. m.</span><small>Atención previa cita</small></div></div><a className="fs-location-row" href="tel:+522723565429"><Phone/><div><b>Teléfono</b><span>272 356 5429</span></div></a></div><Btn href="https://maps.google.com/?q=Norte+6+911+Centro+Orizaba+Veracruz">Cómo llegar</Btn></div>}
function Faq(){return <div className="fs-faq"><span>Preguntas frecuentes</span><h2>Antes de tu cita.</h2>{[['¿Necesito valoración antes de iniciar?','Sí. Nos permite entender tu caso y definir un plan.'],['¿Qué debo llevar?','Ropa cómoda y estudios relacionados, si cuentas con ellos.'],['¿Atienden lesiones deportivas?','Sí, con regreso progresivo a tu actividad.'],['¿El plan es personalizado?','Sí, se construye desde tus objetivos y evolución.']].map(x=><details key={x[0]}><summary>{x[0]}<b>+</b></summary><p>{x[1]}</p></details>)}</div>}
function Contact(){return <Layout><PageTop tag="Contacto" title="Agenda tu" accent="valoración." copy="Cuéntanos qué sientes; no necesitas saber qué tratamiento pedir."/><section className="fs-section"><div className="fs-wrap fs-contact"><Location/><aside><span>Contacto directo</span><h2>Hablemos de tu caso.</h2><a href={WA}><MessageCircle/><div><b>WhatsApp</b><small>272 356 5429</small></div></a><a href="tel:+522723565429"><Phone/><div><b>Llámanos</b><small>272 356 5429</small></div></a><p>Respondemos directamente desde la clínica.</p></aside></div></section><section className="fs-section fs-soft"><div className="fs-wrap"><Faq/></div></section></Layout>}
export function Landing(){const p=location.pathname.replace(/\/$/,'')||'/';if(p==='/servicios')return <Services/>;if(p==='/proceso')return <Process/>;if(p==='/nosotros')return <About/>;if(p==='/blog')return <Blog/>;if(p==='/contacto')return <Contact/>;return <Home/>}
