import {useState} from 'react'
import {Activity,ArrowRight,CalendarDays,Check,ChevronRight,Clock,Dumbbell,HeartPulse,MapPin,Menu,MessageCircle,Phone,ShieldCheck,Stethoscope,Target,Users,X} from 'lucide-react'
import './Landing.css'
const WA='https://wa.me/522723565429?text=Hola%20FYSIKO%2C%20quiero%20agendar%20una%20valoraci%C3%B3n.'
const nav=[['/','Inicio'],['/servicios','Servicios'],['/proceso','Proceso'],['/nosotros','Nosotros'],['/contacto','Contacto']]
function Logo(){return <a className="fs-logo" href="/" aria-label="FYSIKO, inicio"><img src="/fysiko/logo.svg" alt="FYSIKO"/></a>}
function Header(){const[o,setO]=useState(false);return <header className="fs-header"><div className="fs-wrap fs-nav"><Logo/><nav className={o?'open':''}>{nav.map(([h,l])=><a className={location.pathname===h?'active':''} href={h} key={h}>{l}</a>)}<a className="fs-nav-cta" href={WA}><CalendarDays/>Agendar cita</a></nav><button className="fs-menu" onClick={()=>setO(!o)}>{o?<X/>:<Menu/>}</button></div></header>}
function Footer(){return <footer className="fs-footer"><div className="fs-wrap fs-footer-main"><div><Logo/><p>Movimiento real.<br/>Vida sin límites.</p></div><div><b>Explora</b>{nav.slice(1).map(([h,l])=><a href={h} key={h}>{l}</a>)}</div><div><b>Contacto</b><a href="tel:+522723565429">272 356 5429</a><span>Nte. 6 #911, Orizaba, Ver.</span><a href="https://instagram.com/fysiko.rhb">@fysiko.rhb</a></div></div><div className="fs-wrap fs-legal"><span>© {new Date().getFullYear()} FYSIKO.</span><a href="/admin">Acceso administrativo</a></div></footer>}
function Layout({children}:{children:React.ReactNode}){return <main className="fs-site"><Header/>{children}<Footer/><a className="fs-wa" href={WA}><MessageCircle/></a></main>}
function Btn({children,href=WA,outline=false}:{children:React.ReactNode,href?:string,outline?:boolean}){return <a className={'fs-btn '+(outline?'outline':'')} href={href}>{children}<ArrowRight/></a>}
function PageHero({eyebrow,title,accent,copy,image}:{eyebrow:string,title:string,accent:string,copy:string,image:string}){return <section className="fs-page-hero"><div className="fs-wrap"><div><span>{eyebrow}</span><h1>{title}<em>{accent}</em></h1><p>{copy}</p></div><img src={image} alt=""/></div></section>}
function Home(){const pains=[['Dolor lumbar','Espalda y postura'],['Lesiones deportivas','Regresa con seguridad'],['Dolor de cuello','Tensión y movilidad'],['Movilidad limitada','Recupera confianza']];return <Layout>
 <section className="fs-home"><div className="fs-wrap"><div className="fs-home-copy"><span>Fisioterapia en Orizaba</span><h1>Recupera tu <em>movimiento.</em></h1><h2>Vuelve a sentirte bien.</h2><p>Fisioterapia y rehabilitación personalizada para reducir el dolor, recuperar movilidad y volver a tus actividades.</p><Btn>Agendar valoración</Btn></div><div className="fs-home-img"><img src="/fysiko/home-evaluation.webp" alt="Valoración de rodilla"/><small>Evaluación · Tratamiento · Seguimiento</small></div></div></section>
 <section className="fs-trust"><div className="fs-wrap"><span><Stethoscope/>Atención personalizada</span><span><Target/>Enfoque en resultados</span><span><MapPin/>Orizaba, Veracruz</span></div></section>
 <section className="fs-section"><div className="fs-wrap fs-two"><div className="fs-heading"><span>Empieza por lo que sientes</span><h2>¿Qué te impide<br/><em>moverte como antes?</em></h2><p>Conoce las molestias que atendemos y cómo podemos acompañarte.</p></div><div className="fs-pains">{pains.map((p,i)=><a href="/servicios" key={p[0]}><b>0{i+1}</b><div><strong>{p[0]}</strong><span>{p[1]}</span></div><ChevronRight/></a>)}</div></div></section>
 <section className="fs-split"><div className="fs-wrap"><img src="/fysiko/sport-balance.webp" alt="Rehabilitación deportiva"/><div><span>Más que tratamientos</span><h2>Personas en movimiento.</h2><p>Tu plan parte de una valoración real, tus objetivos y las actividades a las que quieres volver.</p><div className="fs-actions"><Btn href="/servicios">Conocer servicios</Btn><Btn href="/proceso" outline>Ver el proceso</Btn></div></div></div></section>
 <section className="fs-close"><div className="fs-wrap"><p>¿No sabes qué tratamiento necesitas?</p><h2>Primero entendamos tu caso.</h2><Btn>Agendar una valoración</Btn></div></section></Layout>}
const services=[['Fisioterapia general','Evaluación y tratamiento individual para dolor, lesiones y limitaciones funcionales.',Stethoscope],['Rehabilitación deportiva','Recuperación y readaptación para volver a entrenar con seguridad.',Activity],['Movilidad articular','Trabajo de movimiento, flexibilidad y control para recuperar función.',Target],['Ejercicio terapéutico','Rutinas guiadas para mejorar fuerza, estabilidad y confianza.',Dumbbell],['Adulto mayor','Acompañamiento para conservar independencia, equilibrio y calidad de vida.',Users],['Prevención de lesiones','Valoración de movimiento y preparación para reducir recaídas.',ShieldCheck]]
function Services(){return <Layout><PageHero eyebrow="Nuestros servicios" title="Tratamientos diseñados" accent="para tu bienestar." copy="Cada plan empieza con una valoración y se adapta a tu vida." image="/fysiko/sport-balance.webp"/><section className="fs-section"><div className="fs-wrap fs-services">{services.map(([n,c,I],i)=>{const Icon=I as typeof Activity;return <article key={n as string}><span>0{i+1}</span><Icon/><h2>{n as string}</h2><p>{c as string}</p><a href={WA}>Consultar servicio <ArrowRight/></a></article>})}</div></section><section className="fs-band"><div className="fs-wrap"><div><span>Atención individual</span><h2>El tratamiento correcto empieza por escucharte.</h2></div><Btn>Agendar valoración</Btn></div></section></Layout>}
const steps=[['Agenda tu valoración','Escríbenos por WhatsApp y elegimos un horario.',CalendarDays],['Evaluamos tu caso','Revisamos dolor, movilidad, antecedentes y objetivos.',Stethoscope],['Definimos un plan','Te explicamos qué trabajaremos y por qué.',Target],['Acompañamos tu avance','Medimos resultados y ajustamos el tratamiento.',HeartPulse]]
function Process(){return <Layout><PageHero eyebrow="Tu recuperación, paso a paso" title="Empieza con una" accent="buena evaluación." copy="Un proceso simple, claro y enfocado en ti." image="/fysiko/home-evaluation.webp"/><section className="fs-section"><div className="fs-wrap fs-process">{steps.map(([t,c,I],i)=>{const Icon=I as typeof Activity;return <article key={t as string}><b>0{i+1}</b><Icon/><div><h2>{t as string}</h2><p>{c as string}</p></div></article>})}</div></section><section className="fs-result"><div className="fs-wrap"><img src="/fysiko/mobility-session.webp" alt="Sesión de movilidad"/><div><span>Seguimiento real</span><h2>Recuperar confianza también es parte del proceso.</h2><p>Buscamos que entiendas tu cuerpo y vuelvas a moverte con seguridad.</p><ul><li><Check/>Objetivos claros</li><li><Check/>Progreso medible</li><li><Check/>Ajustes según tu evolución</li></ul></div></div></section></Layout>}
function About(){return <Layout><PageHero eyebrow="Quiénes somos" title="Movimiento real." accent="Atención humana." copy="Un espacio de fisioterapia en Orizaba enfocado en ayudarte a recuperar calidad de vida." image="/fysiko/mobility-session.webp"/><section className="fs-section"><div className="fs-wrap fs-two"><div className="fs-heading"><span>Nuestra manera de trabajar</span><h2>Primero la persona.<br/><em>Después el tratamiento.</em></h2></div><div className="fs-copy"><p>Cada persona llega con una historia, una actividad y objetivos diferentes. Por eso escuchamos, evaluamos y explicamos antes de iniciar.</p><p>Buscamos avances que se traduzcan en actividades reales: caminar, entrenar, trabajar o volver a hacer lo que disfrutas.</p></div></div></section><section className="fs-values"><div className="fs-wrap">{[['01','Escuchar','Tu experiencia y tus objetivos importan.'],['02','Evaluar','Decidimos desde tu condición real.'],['03','Acompañar','Ajustamos el proceso conforme avanzas.']].map(x=><article key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p></article>)}</div></section></Layout>}
function Contact(){return <Layout><PageHero eyebrow="Estamos en Orizaba" title="Agenda tu" accent="valoración." copy="Cuéntanos qué te pasa y te ayudamos a dar el primer paso." image="/fysiko/home-evaluation.webp"/><section className="fs-section"><div className="fs-wrap fs-contact"><div><span className="fs-overline">Contacto directo</span><h2>Hablemos de tu caso.</h2><p>No necesitas saber qué terapia pedir. Escríbenos qué molestia tienes y desde cuándo.</p><div className="fs-lines"><a href={WA}><MessageCircle/><div><b>WhatsApp</b><span>272 356 5429</span></div></a><a href="tel:+522723565429"><Phone/><div><b>Llámanos</b><span>272 356 5429</span></div></a><a href="https://maps.google.com/?q=Nte.+6+911,+Orizaba,+Veracruz"><MapPin/><div><b>Visítanos</b><span>Nte. 6 #911, entre Oriente 17 y 19<br/>Orizaba, Veracruz</span></div></a><div><Clock/><div><b>Horario</b><span>Lunes a viernes desde las 9:00 a. m.</span></div></div></div></div><aside><span>Agenda tu cita</span><h2>Comienza por una valoración.</h2><p>El botón abrirá WhatsApp con un mensaje listo.</p><Btn>Escribir por WhatsApp</Btn><small>Respondemos directamente desde la clínica.</small></aside></div></section></Layout>}
export function Landing(){const p=location.pathname.replace(/\/$/,'')||'/';if(p==='/servicios')return <Services/>;if(p==='/proceso')return <Process/>;if(p==='/nosotros')return <About/>;if(p==='/contacto')return <Contact/>;return <Home/>}
